INTRODUCTION

**DataFrames**

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

So once you've got your data loaded in, you can have a quick feel for it.

In [4]:
#One's with the head() method
dataset= pd.read_csv("./results.csv")
dataset.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0,0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4,2,Friendly,London,England,False
2,1874-03-07,Scotland,England,2,1,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2,2,Friendly,London,England,False
4,1876-03-04,Scotland,England,3,0,Friendly,Glasgow,Scotland,False

In [5]:
# Or we can use the info instead, it helps us know what's missing in columns.

dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48673 entries, 0 to 48672
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        48673 non-null  object
 1   home_team   48673 non-null  object
 2   away_team   48673 non-null  object
 3   home_score  48673 non-null  int64
 4   away_score  48673 non-null  int64
 5   tournament  48673 non-null  object
 6   city        48673 non-null  object
 7   country     48673 non-null  object
 8   neutral     48673 non-null  bool
dtypes: bool(1), int64(2), object(6)
memory usage: 3.0+ MB

In [8]:
#Then there's the shape attribute, it helps us with a couunt for rows and columns.

dataset.shape

(48673, 9)

In [11]:
#And then there's the describe attribute
dataset.describe()

         home_score    away_score
count  48673.000000  48673.000000
mean       1.757874      1.181743
std        1.772685      1.401651
min        0.000000      0.000000
25%        1.000000      0.000000
50%        1.000000      1.000000
75%        2.000000      2.000000
max       31.000000     21.000000